# Generated by Django 4.1.1 on 2023-10-04 15:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250, verbose_name='Title')),
                ('text', models.TextField(blank=True, null=True)),
                ('published_date', models.DateField(default=django.utils.timezone.now, verbose_name='Published Date')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('published_date', models.DateField(verbose_name='Published Date')),
                ('posted_by', models.CharField(max_length=250, verbose_name='Posted By')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Image')),
                ('document', models.FileField(blank=True, null=True, upload_to='', verbose_name='Document')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('published_date', models.DateField(verbose_name='Published Date')),
                ('posted_by', models.CharField(max_length=250, verbose_name='Posted By')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Image')),
                ('url', models.URLField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('published_date', models.DateField(verbose_name='Published Date')),
                ('image', models.ImageField(upload_to='podcast/', verbose_name='Image')),
                ('host', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('published_date', models.DateField(verbose_name='Published Date')),
                ('author', models.CharField(max_length=250, verbose_name='Author')),
                ('image', models.ImageField(blank=True, null=True, upload_to='releases/', verbose_name='Image')),
                ('document', models.FileField(blank=True, null=True, upload_to='', verbose_name='Document')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('comments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_and_media.comment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
