# Generated by Django 4.1.1 on 2023-10-05 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news_and_media', '0002_alter_comment_options_alter_events_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
