# Generated by Django 4.1.1 on 2023-10-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicsAdvocacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(verbose_name='Overview')),
                ('importance', models.TextField(blank=True, null=True, verbose_name='Importance')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
            ],
        ),
        migrations.CreateModel(
            name='Governance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(verbose_name='Overview')),
                ('importance', models.TextField(blank=True, null=True, verbose_name='Importance')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
            ],
        ),
        migrations.CreateModel(
            name='HealthAdvocacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(verbose_name='Overview')),
                ('importance', models.TextField(blank=True, null=True, verbose_name='Importance')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
            ],
        ),
        migrations.CreateModel(
            name='ParliamentaryMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(verbose_name='Overview')),
                ('importance', models.TextField(blank=True, null=True, verbose_name='Importance')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccountability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(verbose_name='Overview')),
                ('importance', models.TextField(blank=True, null=True, verbose_name='Importance')),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
            ],
        ),
    ]
