# Generated by Django 4.1.1 on 2023-10-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus_areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='economicsadvocacy',
            options={'verbose_name_plural': 'Economics Advocacy'},
        ),
        migrations.AlterModelOptions(
            name='governance',
            options={'verbose_name_plural': 'Governance'},
        ),
        migrations.AlterModelOptions(
            name='healthadvocacy',
            options={'verbose_name_plural': 'Health Advocacy'},
        ),
        migrations.AlterModelOptions(
            name='parliamentarymonitoring',
            options={'verbose_name_plural': 'Parliamentary Monitoring'},
        ),
        migrations.AlterModelOptions(
            name='socialaccountability',
            options={'verbose_name_plural': 'Social Development'},
        ),
    ]
